### PR TITLE
Changes monday afternoon schedule

### PR DESCRIPTION
**Pull request by lucasrenan**
I'm just suggesting a little change for monday afternoon event schedule ;)

### CODE REVIEW

**Comment by lucasrenan** [comment]
@andrebnf @brenolf @mccraveiro @vitorkusiaki review, please.

**Comment by mccraveiro** [comment]
:+1:

**Comment by vitorkusiaki** [comment]
https://cloud.githubusercontent.com/assets/194377/5263503/19704dbe-7a32-11e4-8c93-8c2ef8e9af64.gif

**Comment by brenolf** [comment]
:+1: 
@andrebnf you may want to update the registration schedule before merging

**Comment by andrebnf** [comment]
Thanks @lucasrenan! The schedule is on another repo, since it's using other host for database

**Pull request merged**
